# Set the base image
FROM node:20

# Set working directory
WORKDIR /var/www

# Copy only the necessary files for dependencies installation
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy project files into the docker image
COPY . .

# Build assets if needed (optional for production)
#RUN npm run build

# Expose the port Vite runs on
EXPOSE 3000

# Start the Vite server
CMD ["npm", "run", "dev"]
